server:
  port: 8093

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://admin:admin123@localhost:27017/yanki_db?authSource=admin}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

clients:
  accounts:
    url: ${ACCOUNTS_URL:http://ms-accounts}

resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 2s
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 10
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        register-health-indicator: true
    instances:
      accountsClient:
        base-config: default

logging:
  level:
    root: INFO
    com.banco.yanki: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health,info
