server:
  port: 8095

spring:
  application:
    name: ms-auth

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:cambia-esta-clave-super-secreta-de-al-menos-32-bytes-para-hmac256}
  expiration-seconds: 3600

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.banco.auth: DEBUG
